#
# Outputs
#



#output "kubeconfig" {
#  description = "kubectl config as generated by the module."
#  value = local.kubeconfig
#}


output "cluster_id" {
  description = "EKS cluster ID."
  value       = aws_eks_cluster.demo.id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = aws_eks_cluster.demo.endpoint
}


output "region" {
  description = "AWS region"
  value       = var.aws_region
}

output "kubernetes_cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = aws_eks_cluster.demo.name
}

#output "run_this_command_to_configure_kubectl" {
#  value = "aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)"
#}